// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0N6Mf2oanRLDd1n5UNfnBZKTPAakgf8s',
    appId: '1:1066211105574:web:686081ecbac09ab360bfe7',
    messagingSenderId: '1066211105574',
    projectId: 'endeavour-backend-57d62',
    authDomain: 'endeavour-backend-57d62.firebaseapp.com',
    storageBucket: 'endeavour-backend-57d62.firebasestorage.app',
    measurementId: 'G-40P68VXRG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLCPIHWZlJzh3k9VpAWGubnpRAwmMfHCY',
    appId: '1:1066211105574:android:7f05cee5b9db681560bfe7',
    messagingSenderId: '1066211105574',
    projectId: 'endeavour-backend-57d62',
    storageBucket: 'endeavour-backend-57d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfaXSQ3CmHpHcfq4jK-hwh3axmt0i8z5k',
    appId: '1:1066211105574:ios:f219171f014ec19760bfe7',
    messagingSenderId: '1066211105574',
    projectId: 'endeavour-backend-57d62',
    storageBucket: 'endeavour-backend-57d62.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfaXSQ3CmHpHcfq4jK-hwh3axmt0i8z5k',
    appId: '1:1066211105574:ios:f219171f014ec19760bfe7',
    messagingSenderId: '1066211105574',
    projectId: 'endeavour-backend-57d62',
    storageBucket: 'endeavour-backend-57d62.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0N6Mf2oanRLDd1n5UNfnBZKTPAakgf8s',
    appId: '1:1066211105574:web:60a67ac49cae718b60bfe7',
    messagingSenderId: '1066211105574',
    projectId: 'endeavour-backend-57d62',
    authDomain: 'endeavour-backend-57d62.firebaseapp.com',
    storageBucket: 'endeavour-backend-57d62.firebasestorage.app',
    measurementId: 'G-47M45KV8WT',
  );
}
